version: "3"

services:
  application:
    container_name: application
    build: 
      context: .
    tty: true
    stdin_open: true
  redis:
    container_name: redis
    image: redis:7.4.2
    ports:
      - "6379:6379"